language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

notifications:
  webhooks:
    urls:
    - secure: "GpzH7wXm9NFwOQJ1GfvHJ8aSzW3lUQGf/yYbgvaGpmHxK0Ly/Qjd+vM6AWohsLzHaISoc7M9XLfFfGZujKNt8nD0Pe3XWk076wErBLttHvTK0KyBzZHQ37tSST0KaZB+G6IG3CL24f8ZVZE0MbjnWWyjpLCvmGacv+WDl8O5YGw0Dzp3N9bb8n4cCPQkz04fwOWOCC6CU6CFRPNz2TliEZlARALoEufUrCNGp0dqfSaS70FV7amVWDFfG/IHt1icBkBVfMhnGa/ofo0dPWsMnGW3qrhxAXMwlRB8bMy62kR4wsvYptt3ixdPRDdVBW38/glRF7mUPBhNYJJ93no8ipBx3oqxaxq9txWaHZJ0tNmC8/CdrzkwCcoiVLHBOByF9KMueVn/jcGAILxGeCgS2NxLtCs1uWQWch+rYWjGEpJhTmwxIQ0cW7lJ5BpAsIXoOXwMOSUW9P192gWbGaEVFZ9xTsI3EZFmN3zeGmymHC2zMZpYuMe6fqEDi2l7XT5+GU3eodLqOgpAxUwKkbCP/p4WQyCxeFJAK1fT2WJV8j8B5LxRj7lb3Qq5Hr34UVC7g0ek+/GBqA8xHWg1JeQQzVuPwP2rJB/k/e6HDWKL0HAs1aoW9csncKRMBiHOQfr8+9N05GDQZPYekY7VuawaY+96O+fZZiaDUcLNDsh3J/s="
    on_success: always
    on_failure: always
    on_start: always