language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

notifications:
  webhooks:
    urls:
    - secure: "Hkv+uUm0IXM45kZ1yK9+YK7SZ6grhMpGI6CH90aViwwsxw/M0cxPE6D1fbokG3fCY4IXqwgGbrb1im9AOi4UH6jwElQ7XH40hzgJBTiV8tsyZiNTOMjhpRs+x0AmQpfWq4uwZRKN0OCLF67BnfJYJenxVjrxg1ercK3hFMbAWnbKf92yd7466Zy8bCf0Nkqm0JkgZXaMEJ7LitfJOfBk/+GQyRWqWqV46me9cycEyY5gGDlnCr50VbnAqT8TCc2Iv6TNmP/n28fJlhK0jiLLu/9yF3Tpyo7VWlNiDaJXJdpWHCm1a6yHRaxcdX+Ebg+6RlWNWxQnONwofYxhwwg/2ZZ/am4gC6+UPblIBHyf941LRK69xwf9YBAbQH0LsxdWj/LbMSKHzYd9cNEcHgXIGXcA04EqF7nkjV+YtTQ9t1rXywCx8i473LGZKVZJr7ziEAMqc/gR6w9aICOeJEDfMOEm8WDhhoc1VWc3wxFwN0Q+gLbrEyMM/ZYSkKAaGaYYE9Ef69yJL25+LF72guWLYnZzlunjZNPO393EyAZiJTJ47Z1ybEDzyql/yuM0CpBNLzLzfcqJvegCOKMrtkYWxxP0DczspUVyioEXg54OEzMxM54+Ne8QU3giSzY+6mYHxrzjNyD0C/yRLFsgSHRhjqzeU1dhRj33niJhV2HkZaU="
    on_success: always
    on_failure: always
    on_start: true